// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA755R-14bXHxFNPGOHjXzyywrll96lwqA',
    appId: '1:990928746265:web:fb4ce6a80c958e8c5ff788',
    messagingSenderId: '990928746265',
    projectId: 'flutter-auth-f2c0b',
    authDomain: 'flutter-auth-f2c0b.firebaseapp.com',
    storageBucket: 'flutter-auth-f2c0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZQEDbnZ4-hjaYN4pBGjEfJ_oOi0BvTYw',
    appId: '1:990928746265:android:c26e7fd82db6911b5ff788',
    messagingSenderId: '990928746265',
    projectId: 'flutter-auth-f2c0b',
    storageBucket: 'flutter-auth-f2c0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByq-sOeisO9ahaPST6yklkkiXpZSej89w',
    appId: '1:990928746265:ios:7029018cd5f333775ff788',
    messagingSenderId: '990928746265',
    projectId: 'flutter-auth-f2c0b',
    storageBucket: 'flutter-auth-f2c0b.appspot.com',
    iosClientId: '990928746265-blpme0tstk0ttoroob6r2na913k7nair.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterapp',
  );
}
